### ISSUE TITLE
Chrome: "Uncaught RangeError: Maximum call stack size exceeded" when running in a Web Worker

### ISSUE THREAD

**Issue by aykevl** [jedisct1/libsodium.js#8] opened 2015-04-13 12:48 UTC
See test at http://aykevl.nl/test/sodium-webworker.html.
The page is empty, but in the console an error is logged:

> Uncaught RangeError: Maximum call stack size exceeded

The issue is logged here: https://code.google.com/p/chromium/issues/detail?id=252492
A possible workaround is described here: https://code.google.com/p/crypto-js/issues/detail?id=68

I am using Chrome 41.0.2272.118 (64-bit) on Debian Linux.

**Comment by jedisct1** [comment] 2015-04-20 10:20
Hi,

Thanks for reporting this.

I think the actual issue is that `window`, hence `window.crypto` is not defined in webworkers. It should be `self.crypto`.

I am going to commit a workaround for this.

**Comment by jedisct1** [comment] 2015-04-20 13:07
Should be fixed in 70487753ee25dd761ab8140e4387d2fbb7f749da

Thanks!

**Comment by aykevl93** [comment] 2015-04-27 12:17
I've updated the libsodium version but it still gives the same error.
Have you tested in Chrome? Firefox doesn't give the RangeError but says "InternalError: uncaught exception: No secure random number generator found" (which looks like an unrelated issue to me, see [bug 842818](https://bugzilla.mozilla.org/show_bug.cgi?id=842818) in Firefox).

**Comment by jedisct1** [comment] 2015-04-27 12:46
On the Chrome issue: try loading `sodium.js` (non-minified), not the minified version. I think the issue is due to UglifyJS.

**Comment by aykevl93** [comment] 2015-04-27 12:58
How should I use it? When I use [dist/modules/libsodium.js](https://github.com/jedisct1/libsodium.js/blob/master/dist/modules/libsodium.js) `sodium` is not defined.

**Comment by jedisct1** [comment] 2015-04-27 13:27
`modules/libsodium.js` is for apps using modules. It doesn't define anything in the global namespace.

Just realized that the combined version was available non-minified in the git repos.
Here you go:
https://raw.githubusercontent.com/jedisct1/libsodium.js/master/dist/browsers/combined/sodium.js

**Comment by aykevl93** [comment] 2015-04-27 14:26
Yes, using the non-minified version fixes the issue. Thank you!

**Closed** 2015-06-16 12:57 UTC

**Comment by cocheok** [comment] 2015-11-09 21:14
is it fixed in mozilla?

**Comment by BatikhSouri** [comment] 2015-11-11 14:25
This issue in particular should be fixed now. But yet, using Libsodium.js in a WebWorker is not really possible without modifying it, especially because of [this line](https://github.com/jedisct1/libsodium/blob/master/src/libsodium/randombytes/randombytes.c#L92).

Could we throw an error on call instead of throwing simply when loading libsodium into the WebWorker? Something like jedisct1/libsodium#320 ?
