### ISSUE TITLE
crypto_pwhash returns incorrect output on its first execution with Argon2id on mobile when using more than 8 MB of memory 

### ISSUE THREAD

**Issue by gustavotoyota** [jedisct1/libsodium.js#311] opened 2023-02-09 19:23 UTC
For some reason crypto_pwhash returns a random output on its first execution on mobile when using more than 8 MB of memory on Argon2id. My goal is to use 32 MB of memory on all platforms. I'm using Capacitor to build mobile from Javascript. On Desktop it executes without a problem.

I tested with the library argon2-browser and it works correctly, but I'm using other Sodium features and was hoping to not need other cryptography libraries.

I would expect an error or something similar, but the function just decides to return a random value. What could it be? Is there a workaround for this without wasting the first execution? Thank you.

**Comment by gustavotoyota** [comment] 2023-02-09 19:44
More info: It happens more than once sometimes. It's deterministic in a certain way: The first incorrect output is always the same, and the second incorrect output is always the same, but the second incorrect output is different than the first incorrect output.

**Comment by jedisct1** [comment] 2023-02-09 20:22
Is that when using WebAssembly, or JavaScript?

**Comment by gustavotoyota** [comment] 2023-02-09 20:34
Using WebAssembly.
![Screenshot from 2023-02-09 16-32-15](https://user-images.githubusercontent.com/11639451/217930656-c627df37-679a-4f35-9f35-52efaf9fb017.png)

**Comment by jedisct1** [comment] 2023-02-09 22:50
Do you have a minimal code snippet that reproduces this?

Can it be reproduced with `node` or `bun`?

**Comment by gustavotoyota** [comment] 2023-02-13 19:11
> Can it be reproduced with `node` or `bun`?
It only happens on the mobile app built through Capacitor.
I think Capacitor is built on top of node.

> Do you have a minimal code snippet that reproduces this?
I won't be able to put together a minimal reproduction in the near future.

**Comment by jedisct1** [comment] 2023-02-16 18:08
I think you are actually not using WebAssembly, and this is a duplicate of #310

**Closed by jedisct1** 2023-02-16 18:08 UTC
