### ISSUE TITLE
crypto_pwhash() returns buffer of null bytes 

### ISSUE THREAD

**Issue by paraboul** [jedisct1/libsodium.js#235] opened 2020-03-11 21:44 UTC
I was testing some code using libsodium-wrappers (not the sumo version) inside Blisk (https://blisk.io/) which uses Chromium.

This code :

```
sodium.crypto_pwhash(32, password, "0000000000000000",
    sodium.crypto_pwhash_OPSLIMIT_INTERACTIVE, 
    sodium.crypto_pwhash_MEMLIMIT_INTERACTIVE,
    sodium.crypto_pwhash_ALG_DEFAULT)
```

is returning a buffer of the expected size but filled with only zero bytes. `Uint8Array(32) [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]`.

Lowering `memlimit` makes it work as expected.

The same code works properly on "regular" Chrome, so probably some memory limits triggered on Blisk.

I'd expect it to throw an error in case of memory exhaustion without having me to check the content of the returned buffer.
I can see an "Invalid Operation" exception in case of memlimit being too small for instance. So error are being reported.

Any idea?

Thanks!

**Comment by paraboul** [comment] 2020-03-11 23:02
My guess is that no `errno` is set here :

https://github.com/jedisct1/libsodium/blob/9f14962388ceb795114405ba8f7af59d5bc43b1b/src/libsodium/crypto_pwhash/argon2/pwhash_argon2i.c#L172

**Comment by jedisct1** [comment] 2020-03-12 14:58
Do you know whether it is using the WebAssembly code or the JavaScript one?

**Comment by paraboul** [comment] 2020-03-12 16:37
WebAssembly is probably turned off it seems.
I tried the same test case in chrome w/o wasm (`--js-flags=--noexpose_wasm`), turns out it exposes the same issues

**Comment by jedisct1** [comment] 2023-02-16 19:24
Probably a duplicate of #310

**Closed by jedisct1** 2023-02-16 19:24 UTC
