### ISSUE TITLE
Incorrect constant values

### ISSUE THREAD

**Issue by ForbesLindesay** [jedisct1/libsodium.js#161] opened 2018-07-12 14:10 UTC
I'm trying to use this in node v10.3.0 and some of the constants don't seem to have the correct values:

```js
const s = require('libsodium-wrappers');
await s.ready;
console.log(s.crypto_pwhash_PASSWD_MAX);
// -1
console.log(s.crypto_pwhash_MEMLIMIT_MAX);
// => -2147483648
```

I'm pretty sure these values should be positive.

**Comment by jedisct1** [comment] 2018-07-12 14:19
I think it is a duplicate of https://github.com/jedisct1/libsodium.js/issues/121 and it should have been  fixed by https://github.com/jedisct1/libsodium.js/commit/d6f8c8f628f0084798235e48534eb9d6f0fa0493

**Comment by jedisct1** [comment] 2018-07-13 16:35
Still hoping for https://github.com/kripken/emscripten/issues/6387 to be solved :(

**Closed** 2018-09-29 15:52 UTC
